lsdss/lsdss/accounts/urls.py
from django.urls import path
from accounts import views
app_name ='accounts'
urlpatterns=[
    path('signup',views.signup,name='signup'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
]

lsdss/lsdss/appAdmin/urls.py
from django.urls import path,include
from appAdmin import views
app_name="adminApp"
urlpatterns=[
    path("",views.registerData,name="register"),
    path("appAdmin",views.adminApp,name="adminHome"),
    path("appAdmin/users",views.usersList,name="users"),
    path("appAdmin/owners",views.ownersList,name="owners"),
    path("appAdmin/deleteAllData",views.deleteAllData,name="deleteAllData"),
]

lsdss/lsdss/lsdss/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("appAdmin.urls",namespace="adminApp")),
    # path('admin/', include("adminApp.urls",namespace="admin-app")),
    path('owner/', include("owner.urls",namespace="owner")),
    path('user/', include("user.urls",namespace="user")),
    path('tpa/', include("tpa.urls",namespace="tpa")),
    path('encDec/', include("encdec.urls",namespace="encdec")),
    path('accounts/', include("accounts.urls",namespace="accounts")),
    path('cloud/', include("cloud.urls",namespace="cloud")),
] 


if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_URL)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_URL)

lsdss/lsdss/tpa/urls.py
from django.urls import path,include
from tpa import views
app_name="tpa"
urlpatterns=[
    path("",views.Home,name="home"),
    path("ownerkey/",views.ownerKey,name="ownerkey"),
    path("ownerkey/<int:id>",views.generatePubKey,name="generatePubKey"),
    path("ownerkey/<int:id>/sent",views.sendPubKey,name="sendPubKey"),
    path("userkey",views.userKey,name="userkey"),
    path("userkey/<int:id>",views.generateUserPubKey,name="generateUserPubKey"),
    path("userkey/<int:id>/sent",views.sendUserPubKey,name="sendUserPubKey"),
    path("ownerUploadedFiles",views.ownerUploadedFiles,name="ownerUploadedFiles"),
]

lsdss/lsdss/appAdmin/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
import base64

modules=(('Owner','Owner'),('User','User'),('tpa','tpa'),('admin','admin'),('espdsp','espdsp'),('cloud','cloud'))

class register(models.Model):
    user=models.OneToOneField(User,unique=True,on_delete=models.CASCADE)
    mobile = models.CharField(max_length=10)
    city = models.CharField(max_length=15)
    address = models.CharField(max_length=200)
    module = models.CharField(max_length=20, choices=modules)
    strdate = models.DateField(auto_now_add=True)

    def __str__(self):
        return str(self.user)


class DOTATransaction(models.Model):
    owner_name=models.CharField(max_length=30)
    attributes=models.ForeignKey(register,on_delete=models.CASCADE)
    pub_key=models.CharField(max_length=300)
    # _pub_key=models.CharField(max_length=300)

    # def set_data(self, data):
    #     self._pub_key = base64.encodestring(data)

    # def get_data(self):
    #     return base64.decodestring(self._pub_key)

    # pub_key = property(get_data, set_data)
    status=models.CharField(max_length=20)

    def __str__(self):
        return self.owner_name


class ownerFileUpload(models.Model):
    owner_name=models.CharField(max_length=30,null=True,blank=True)
    file_name=models.CharField(max_length=30)
    owner_file=models.FileField(upload_to='media')
    file_status=models.CharField(max_length=30)
    file_upload_date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.file_name

class DOESPTransaction(models.Model):
    # owner=models.ForeignKey(ownerFileUpload,on_delete=models.CASCADE)
    owner_name=models.CharField(max_length=30)
    file_name=models.CharField(max_length=30)
    file_path=models.CharField(max_length=100)
    pub_key=models.CharField(max_length=300)
    status=models.CharField(max_length=30)
    enc_file=models.CharField(max_length=100)
    reEnc_file=models.CharField(max_length=100,blank=True,null=True)

    def __str__(self):
        return self.file_name

class cloudTransaction(models.Model):
    owner_name=models.CharField(max_length=30)
    file_name=models.CharField(max_length=30)
    enc_file=models.CharField(max_length=100)
    pub_key=models.CharField(max_length=300)
    status=models.CharField(max_length=30)
    attributes=models.CharField(max_length=500)
    policies=models.CharField(max_length=500)
    downloadCount=models.PositiveIntegerField()

    def __str__(self):
        return self.file_name

#Owner and User Transaction
class DODUTransaction(models.Model):
    owner_name=models.CharField(max_length=30)
    file_name=models.CharField(max_length=30)
    attributes=models.CharField(max_length=500)
    user_list=models.CharField(max_length=500)
    status=models.CharField(max_length=30)
    
    def __str__(self):
        return self.owner_name

# User Transaction
class DUTATransaction(models.Model):
    user_name=models.CharField(max_length=30)
    attributes=models.ForeignKey(register,on_delete=models.CASCADE)
    pub_key=models.CharField(max_length=300)
    status=models.CharField(max_length=20)

    def __str__(self):
        return self.user_name

class DUCTransaction(models.Model):
    owner_name=models.CharField(max_length=30)
    user_name=models.CharField(max_length=30)
    pub_key=models.CharField(max_length=300)
    attributes=models.CharField(max_length=500)
    status=models.CharField(max_length=30)
    file_name=models.CharField(max_length=30,null=True,blank=True)
    enc_file=models.CharField(max_length=300)
    

    def __str__(self):
        return self.user_name

class DUCDECTransaction(models.Model):
    owner_name=models.CharField(max_length=30)
    user_name=models.CharField(max_length=30)
    pub_key=models.CharField(max_length=300)
    status=models.CharField(max_length=30)
    file_name=models.CharField(max_length=30)
    enc_file=models.CharField(max_length=300)
    dec_file=models.CharField(max_length=300)

    def __str__(self):
        return self.user_name

lsdss/lsdss/appAdmin/forms.py
from appAdmin.models import register, ownerFileUpload,cloudTransaction,DUCTransaction
from django.contrib.auth.models import User
from django import forms

class registerForm(forms.ModelForm):

    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=20, widget=forms.widgets.PasswordInput)
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)
    email = forms.EmailField()
    # address=forms.CharField(max_length=200,widget=forms.Textarea)

    class Meta:
        model = register
        fields=['username','password','first_name','last_name','city','email','mobile','address','module']


class ownerFileUploadForm(forms.ModelForm):

    class Meta:
        model=ownerFileUpload
        fields=['file_name','owner_file']


class cloudFileUploadForm(forms.ModelForm):

    class Meta:
        model=cloudTransaction
        fields=['attributes','policies']

class DUCTransactionForm(forms.ModelForm):

    class Meta:
        model=DUCTransaction
        fields=['attributes']

lsdss/lsdss/appAdmin/views.py
from django.shortcuts import render
from appAdmin.forms import registerForm
from appAdmin.models import *
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.
def registerData(request):
    form=registerForm()
    context={'form':form}
    return render(request,"index.html",context)

def adminApp(request):
    context={}
    return render(request,'admin/adminHome.html',context)

def usersList(request):
    users=register.objects.all().filter(module="User")
    context={'users':users}
    return render(request,'admin/viewUsers.html',context)

def ownersList(request):
    owners=register.objects.all().filter(module="Owner")
    context={'owners':owners}
    return render(request,'admin/viewOwners.html',context)

def deleteAllData(request):
    DOTATransaction.objects.all().delete()
    ownerFileUpload.objects.all().delete()
    DOESPTransaction.objects.all().delete()
    cloudTransaction.objects.all().delete()
    DODUTransaction.objects.all().delete()
    DUTATransaction.objects.all().delete()
    DUCTransaction.objects.all().delete()
    DUCDECTransaction.objects.all().delete()
    deleted="deleted"
    context={'deleted':deleted}
    return HttpResponseRedirect(reverse("adminApp:adminHome"))

lsdss/lsdss/appAdmin/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'css/style.css' %}">
    <link rel="stylesheet" href="{%static 'css/landing.css' %}">
    <link rel="stylesheet" href="{%static 'css/owner.css' %}">

    <title>{% block title%} {{title}} {% endblock %}</title>
</head>
<body>
        <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
                <a class="navbar-brand" href="#">{%block logo%}  {% endblock %}</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
              
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        {% block navMenu %}

                        {% endblock %}
                  
                </div>
              </nav>

        </header>
        
    {% block content %}
        
    {% endblock %}

    <!-- <footer class="footer navbar-fixed-bottom">
            &copy; LSDSS
    </footer> -->
   
    

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

<script src="{%static '/js/main.js'%}"></script>
</body>
</html>

lsdss/lsdss/appAdmin/templates/index.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %}
{%block logo%} Light Secure Data Sharing Scheme {% endblock %}
{% block navMenu %}

<ul class="navbar-nav ml-auto ">
        <li class="nav-item active">
          <a class="nav-link" href="{%url 'adminApp:register'%}">Home <span class="sr-only">(current)</span></a>
        </li>

        <!-- <li class="nav-item">
          <a class="nav-link" href="{%url 'adminApp:adminHome'%}">Admin <span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item ">
                <a class="nav-link" href="{% url 'owner:home' %}">Owner<span class="sr-only">(current)</span></a>
        </li>

       <li class="nav-item ">
            <a class="nav-link" href="{%url 'user:home' %}">User <span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item ">
            <a class="nav-link" href="{%url 'tpa:home' %}">TPA <span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item ">
            <a class="nav-link" href="{%url 'encdec:home' %}">Cryptography Manager <span class="sr-only">(current)</span></a>
        </li> -->

       
        <button type="button" class="btn btn-primary" data-dismiss="modal" 
    data-toggle="modal" data-modal="registerModal" id="registerButton"  data-target="#registerModal">Register/Login</button>

        <!-- <button class="btn btn-primary" class="showFormButton"  id="loginButton" >Login</button> -->
        <!-- <button class="btn btn-primary" class="showFormButton"  id="registerButton" >Register/Login</button> -->

        <!-- <button type="button" class="btn btn-primary" data-dismiss="modal" 
    data-toggle="modal" data-modal="loginModal" id="loginButton"  data-target="#loginModal">Login</button> -->

      </ul>

 {% endblock %}


{% block content %}
{% if error %}
      {{error}}
{% endif %}

      <div class="mt-2 proCarousel">

      
        <div id="carouselExampleSlidesOnly" class="carousel slide " data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="https://open-stand.org/wp-content/uploads/2017/12/Screen-Shot-2017-12-06-at-10.42.09-AM.png" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                    <img src="http://solopracticeuniversity.com/files/2018/04/cyber-security.png" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                    <img src="https://e-channelnews.com/wp-content/uploads/2018/05/CloudSecurity2-696x348.jpg" class="d-block w-100" alt="...">
                    </div>

                    <div class="carousel-item">
                    <img src="https://i.kinja-img.com/gawker-media/image/upload/s--SGs2aMWj--/c_scale,f_auto,fl_progressive,q_80,w_800/jgpeuoavmn7pwbh98ycs.jpg" class="d-block w-100" alt="...">
                    </div>
                </div>
        </div>
      </div>
        
       
    <div class="card container mt-2 mb-2">
        <div class="card-title"></div>
        <div class="card-content">

            Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos tempore suscipit minus consequatur eligendi dolor accusamus! Optio, iste quod earum natus doloremque quia. Quam velit ab error exercitationem. Laudantium, debitis.
        </div>
    </div>

    

    <!-- Modal -->
<div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="false">
    <div class="modal-dialog  modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalCenterTitle">Register/Login</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">

            <nav>
                <div class="nav nav-tabs" id="nav-tab" role="tablist">
                  <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Register</a>
                  <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Login</a>
                  <!-- <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Contact</a> -->
                </div>
              </nav>
              <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                    <div class="container">

                    
                        <form action="{%url 'accounts:signup'%}" method="POST" class="mt-2" id="registerForm" >
                            {% csrf_token %}
                            <div class="form-group">
                              
                                <div class="row">
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                      <input type="text" class="form-control" name="username" required id="id_username" placeholder="Username">
                                    </div>
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                      <input type="password" class="form-control" name="password" required id="id_password" placeholder="Password">
                                    </div>
                                </div>
                                <br>
                                <div class="row">
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                      <input type="text" class="form-control" name="first_name" required id="id_first_name" placeholder="First Name">
                                    </div>
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                      <input type="text" class="form-control" name="last_name" required id="id_last_name" placeholder="Last Name">
                                    </div>
                                </div>
                                <br>
                                <div class="row">
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                      <input type="text" class="form-control" name="email" required id="id_email" placeholder="Email">
                                    </div>
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                      <input type="text" class="form-control" name="mobile" required id="id_mobile" placeholder="Mobile">
                                    </div>
                                </div>
                                <br>
                                <div class="row">
                                    <textarea  class="form-control" name="address" required id="id_address" rows="5" cols="60" placeholder="Address"></textarea>
                                </div>
                                <br>
                                <div class="row">
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                        <input type="text" class="form-control" name="city" required id="id_city" placeholder="City">
                                      </div>
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                        <div class="form-group">
                                            <!-- <label for="">Role</label> -->
                                            <select class="form-control" name="module" required id="id_module">
                                              <option value="-1">Select Role</option>
                                              <option value="Owner">Owner</option>
                                              <option value="User">User</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                  <input type="submit" value="Register" class="btn btn-primary" id="registerData">
                                
                                    <!-- <button type="submit" class="btn btn-primary " id="registerData">Register</button> -->
                                 
                                  </div>
                                
                          </form>                        
                </div>
                </div>
                <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                  
                    <form action="{%url 'accounts:login'%}" class="mt-4" id="loginForm" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                          
                          <div class="row">
                              <div class="offset-xl-2 col-xl-8 offset-lg-2 col-lg-8 offset-md-2 col-md-8 col-sm-6 col-12">
                                <input type="text" class="form-control" name="loginUsername" id="id_loginUsername" placeholder="Username"><br>
                              </div>
                              <div class="offset-xl-2 col-xl-8 offset-lg-2 col-lg-8 offset-md-2 col-md-8 col-sm-6 col-12">
                                <input type="password" class="form-control" name="loginPassword" id="id_loginPassword" placeholder="Password">
                              </div>
                          </div>  
                          
                            <button type="submit" class="btn btn-primary offset-xl-2 mt-2">Login</button>
                          
                    </form>
                </div>
               
              </div>

            

                
                </div>
        </div> <!-- end of modal body -->
        
      </div>
  </div> <!-- end of register modal -->


  
{% endblock %}