lsdss/lsdss/accounts/urls.py
from django.urls import path
from accounts import views
app_name ='accounts'
urlpatterns=[
    path('signup',views.signup,name='signup'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
]

lsdss/lsdss/lsdss/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("appAdmin.urls",namespace="adminApp")),
    # path('admin/', include("adminApp.urls",namespace="admin-app")),
    path('owner/', include("owner.urls",namespace="owner")),
    path('user/', include("user.urls",namespace="user")),
    path('tpa/', include("tpa.urls",namespace="tpa")),
    path('encDec/', include("encdec.urls",namespace="encdec")),
    path('accounts/', include("accounts.urls",namespace="accounts")),
    path('cloud/', include("cloud.urls",namespace="cloud")),
] 


if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_URL)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_URL)

lsdss/lsdss/owner/urls.py
from django.urls import path,include
from owner import views
from django.conf import settings
from django.conf.urls.static import static
app_name="owner"
urlpatterns=[
    path("",views.Home,name="home"),
    path("manageKey",views.keyManagement,name="keyManagement"),
    path("cryptography",views.cryptography,name="cryptography"),
    path("uploadFile",views.uploadFile,name="uploadFile"),
    path("deleteFile/<int:id>",views.uploadedFileDelete,name="uploadedFileDelete"),
    path("encryptFile/<int:id>",views.sendFiletoEncryption,name="sendFiletoEncryption"),
    path("uploadFiletoCloud/<int:id>",views.uploadFiletoCloud,name="uploadFiletoCloud"),
    path("uploadedFile",views.uploadedFile,name="uploadedFile"),
    path("userList",views.showUserList,name="showUserList"),
    path("revocationNotification",views.revocationNotification,name="revocationNotification"),
    path("revocation/<int:id>",views.revocation,name="revocation"),
    # Re-encrypted Files
    path("reEncrypted",views.reEncryptedFile,name="reEncryptedFile"),
    path("uploadREFiletoCloud/<int:id>",views.uploadREFiletoCloud,name="uploadREFiletoCloud"),
]

# if settings.DEBUG:
#     urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lsdss/lsdss/tpa/urls.py
from django.urls import path,include
from tpa import views
app_name="tpa"
urlpatterns=[
    path("",views.Home,name="home"),
    path("ownerkey/",views.ownerKey,name="ownerkey"),
    path("ownerkey/<int:id>",views.generatePubKey,name="generatePubKey"),
    path("ownerkey/<int:id>/sent",views.sendPubKey,name="sendPubKey"),
    path("userkey",views.userKey,name="userkey"),
    path("userkey/<int:id>",views.generateUserPubKey,name="generateUserPubKey"),
    path("userkey/<int:id>/sent",views.sendUserPubKey,name="sendUserPubKey"),
    path("ownerUploadedFiles",views.ownerUploadedFiles,name="ownerUploadedFiles"),
]

lsdss/lsdss/appAdmin/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
import base64

modules=(('Owner','Owner'),('User','User'),('tpa','tpa'),('admin','admin'),('espdsp','espdsp'),('cloud','cloud'))

class register(models.Model):
    user=models.OneToOneField(User,unique=True,on_delete=models.CASCADE)
    mobile = models.CharField(max_length=10)
    city = models.CharField(max_length=15)
    address = models.CharField(max_length=200)
    module = models.CharField(max_length=20, choices=modules)
    strdate = models.DateField(auto_now_add=True)

    def __str__(self):
        return str(self.user)


class DOTATransaction(models.Model):
    owner_name=models.CharField(max_length=30)
    attributes=models.ForeignKey(register,on_delete=models.CASCADE)
    pub_key=models.CharField(max_length=300)
    # _pub_key=models.CharField(max_length=300)

    # def set_data(self, data):
    #     self._pub_key = base64.encodestring(data)

    # def get_data(self):
    #     return base64.decodestring(self._pub_key)

    # pub_key = property(get_data, set_data)
    status=models.CharField(max_length=20)

    def __str__(self):
        return self.owner_name


class ownerFileUpload(models.Model):
    owner_name=models.CharField(max_length=30,null=True,blank=True)
    file_name=models.CharField(max_length=30)
    owner_file=models.FileField(upload_to='media')
    file_status=models.CharField(max_length=30)
    file_upload_date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.file_name

class DOESPTransaction(models.Model):
    # owner=models.ForeignKey(ownerFileUpload,on_delete=models.CASCADE)
    owner_name=models.CharField(max_length=30)
    file_name=models.CharField(max_length=30)
    file_path=models.CharField(max_length=100)
    pub_key=models.CharField(max_length=300)
    status=models.CharField(max_length=30)
    enc_file=models.CharField(max_length=100)
    reEnc_file=models.CharField(max_length=100,blank=True,null=True)

    def __str__(self):
        return self.file_name

class cloudTransaction(models.Model):
    owner_name=models.CharField(max_length=30)
    file_name=models.CharField(max_length=30)
    enc_file=models.CharField(max_length=100)
    pub_key=models.CharField(max_length=300)
    status=models.CharField(max_length=30)
    attributes=models.CharField(max_length=500)
    policies=models.CharField(max_length=500)
    downloadCount=models.PositiveIntegerField()

    def __str__(self):
        return self.file_name

#Owner and User Transaction
class DODUTransaction(models.Model):
    owner_name=models.CharField(max_length=30)
    file_name=models.CharField(max_length=30)
    attributes=models.CharField(max_length=500)
    user_list=models.CharField(max_length=500)
    status=models.CharField(max_length=30)
    
    def __str__(self):
        return self.owner_name

# User Transaction
class DUTATransaction(models.Model):
    user_name=models.CharField(max_length=30)
    attributes=models.ForeignKey(register,on_delete=models.CASCADE)
    pub_key=models.CharField(max_length=300)
    status=models.CharField(max_length=20)

    def __str__(self):
        return self.user_name

class DUCTransaction(models.Model):
    owner_name=models.CharField(max_length=30)
    user_name=models.CharField(max_length=30)
    pub_key=models.CharField(max_length=300)
    attributes=models.CharField(max_length=500)
    status=models.CharField(max_length=30)
    file_name=models.CharField(max_length=30,null=True,blank=True)
    enc_file=models.CharField(max_length=300)
    

    def __str__(self):
        return self.user_name

class DUCDECTransaction(models.Model):
    owner_name=models.CharField(max_length=30)
    user_name=models.CharField(max_length=30)
    pub_key=models.CharField(max_length=300)
    status=models.CharField(max_length=30)
    file_name=models.CharField(max_length=30)
    enc_file=models.CharField(max_length=300)
    dec_file=models.CharField(max_length=300)

    def __str__(self):
        return self.user_name

lsdss/lsdss/owner/models.py
from django.db import models

# Create your models here.

lsdss/lsdss/owner/views.py
from django.shortcuts import render,get_object_or_404,render_to_response,redirect
from appAdmin.models import register,DOTATransaction,ownerFileUpload,DOESPTransaction,cloudTransaction,DODUTransaction
from django.contrib.auth.models import User
from appAdmin.forms import ownerFileUploadForm,cloudFileUploadForm
from django.http import HttpResponseRedirect ,HttpResponse
from django.urls import reverse
from django.template.loader import render_to_string
from django.core.files.storage import FileSystemStorage
# from .models import ModelWithFileField
# Create your views here.
def Home(request):
    username=request.session['username']
    request.session['username']=username

    context={}
    return render(request,"owner/home.html",context)

def keyManagement(request):
    username=request.session['username']
    print(username)

    user_attributes_list=[]
    users=User.objects.filter(username=username)
    for user in users:
        user_attributes=register.objects.filter(user=user.id)
        for usr in user_attributes:
            user_attributes_list.append(usr.user.username)
            user_attributes_list.append(usr.user.email)
            user_attributes_list.append(usr.mobile)
        #     print(usr.user.username,usr.user.first_name,usr.user.last_name,usr.mobile)
            print("uattr-",user_attributes_list)
    status="No Key Requested"
    pub_Key=""
    dota_trans=DOTATransaction.objects.filter(owner_name=username)
    if dota_trans is not None:
        for dota in dota_trans:
            status=dota.status
            pub_Key=dota.pub_key

    context={'user_attributes':user_attributes,'status':status,'pub_Key':pub_Key}
    # return render(request,"owner/managekey.html",context)
    if request.method=='POST':
        # dotaTransaction=DOTATransaction()
        status="Key Requested"
        owner_name=username
        attributes=user_attributes_list
        status=status
        pub_Key=pub_Key
        dota=DOTATransaction(owner_name=username,attributes=register.objects.get(user=user.id),status=status,pub_key=pub_Key)
        dota.save()
        dota_trans=DOTATransaction.objects.filter(owner_name=owner_name)
        for dota in dota_trans:
            status=dota.status
            pub_Key=dota.pub_key
            print('dota--',dota.status)
        print("attr-",attributes)
        print('sta-',status)
        context={'dota_trans':dota_trans,'user_attributes':user_attributes,'status':status,'pub_Key':pub_Key}
        return render(request,"owner/managekey.html",context)
    else:
        status=status
        return render(request,"owner/managekey.html",context)


def cryptography(request):
    userFile=""
    status=""
    username=request.session['username']
    ufiles=ownerFileUpload.objects.filter(owner_name=username)
    for ufile in ufiles:
        userFile=ufile.owner_file.url
        status=ufile.file_status
    print(status)
    doespData=DOESPTransaction.objects.filter(owner_name=username)
    context={'doespData':doespData,'userFile':userFile,'status':status}
    return render(request,"owner/cryptography.html",context)

def uploadFile(request):
    username=request.session['username']
    print(username)
    uploaded=False
    form=ownerFileUploadForm()
    doespData=DOESPTransaction.objects.filter(owner_name=username)
    for doesp in doespData:
        status=doesp.status
        print(status)
    context={'form':form }
    if request.method=='POST':
        if 'uploadFileBtn' in request.POST:
            print('I m upload...')
            form=ownerFileUploadForm(request.POST or None,request.FILES)
            if form.is_valid():
                owner_name=username
                ofname=request.POST.get('file_name')
                ofile=request.FILES.get('owner_file')
                fs = FileSystemStorage()
                filename = fs.save(ofile.name, ofile)
                uploaded_file_url = fs.url(filename)
                ofileName=ofile.name
                print(ofileName)
                file_status=""
                fuForm=ownerFileUpload(owner_name=username,file_name=ofname,owner_file=ofileName,file_status=file_status)
                fuForm.save()
                print('uploaded')
                uploaded=True
                files=ownerFileUpload.objects.all().filter(owner_name=username)
                context={'form':form,'uploaded':uploaded,'files':files,'uploaded_file_url':uploaded_file_url}
                # return render(request,"owner/uploadFile.html",context)
                return HttpResponseRedirect(reverse('owner:uploadFile'))
            else:
                print("Form invalid")
                print(form.errors)
                context={'form':form}
                return render(request,"owner/uploadFile.html",context)
        else:
            print('I m upload...get')
            context={'uploaded_file_url':uploaded_file_url}
            return render(request,"owner/uploadFile.html",context)


    else:
        files=ownerFileUpload.objects.all().filter(owner_name=username)
        context={'form':form,'files':files}
        return render(request,"owner/uploadFile.html",context)

def uploadedFileDelete(request,id):
    username=request.session['username']
    selected_file=get_object_or_404(ownerFileUpload,pk=id)
    selected_file.delete()
    print('deleted')
    files=ownerFileUpload.objects.all().filter(owner_name=username)
    context={'files':files}
    return render(request,"owner/uploadFile.html",context)

# Uploaded to cloud
def uploadedFile(request):
    username=request.session['username']
    status="File Uploaded"
    cloudData=cloudTransaction.objects.filter(owner_name=username,status = status)
    print(cloudData)
    uType="User"
    userList=[]
    curStatus=''
    # context={'doespData':doespData}
    users=register.objects.filter(module=uType)
    owner_name=username
    usersList=''
    if request.method=="POST":

        cloudData=cloudTransaction.objects.filter(owner_name=owner_name,status = status)
        for cdata in cloudData:
            file_name=cdata.file_name
            attributes=cdata.attributes
        userListMembers=request.POST.getlist('userCheckbox')
        userList.append(userListMembers)
        userListData=",".join(str(user) for user in userList)
        status="Data Shared"
        print(userListData)
        dodudata=DODUTransaction(owner_name=owner_name,file_name=file_name,attributes=attributes,user_list=userListData,status=status)
        dodudata.save()
        context={'users':users,'cloudData':cloudData}
        return render(request,"owner/uploadedFile.html",context)
    else:
        status="Data Shared"
        dodudatas=DODUTransaction.objects.filter(owner_name=owner_name,status = status)
        for dodudata in dodudatas:
            curStatus=dodudata.status
            usersList=dodudata.user_list
            print(curStatus)
            # users=str(usersList).split(',')
            print(usersList)
            # for u in users:
            #     print(u)
        context={'users':users,'cloudData':cloudData,'curStatus':curStatus,'usersList':usersList}
        return render(request,"owner/uploadedFile.html",context)


def sendFiletoEncryption(request,id):
    username=request.session['username']
    dotaData=DOTATransaction.objects.filter(owner_name=username)
    for dota in dotaData:
        pub_key=dota.pub_key
    selected_file=get_object_or_404(ownerFileUpload,pk=id)
    owner_name=username
    file_name=selected_file.file_name
    file_path=selected_file.owner_file.url
    status="File to Encrypt"
    form=DOESPTransaction()
    context={'form':form}
    enc_file=""
    if request.method=="POST":
        status="File sent for Encryption"
        form=DOESPTransaction(owner_name=owner_name,file_name=file_name,file_path=file_path,pub_key=pub_key,status=status,enc_file=enc_file)
        form.save()
        print('form sent')
        file_status=status
        doespUpdate=ownerFileUpload.objects.filter(id=id).update(file_status=status)
        print("status updated")
        context={'form':form,'status':status,'file_status':file_status}
        # return render(request,"owner/cryptography.html",context)
        return HttpResponseRedirect(reverse('owner:uploadFile'))
    else:
        # form=DOESPTransaction()
        print('invalid form')
        # print(form.errors)
        files=ownerFileUpload.objects.all().filter(owner_name=username)
        context={'files':files,'form':form,'status':status}
        return render(request,"owner/uploadFile.html",context)

def uploadFiletoCloud(request,id):
    # attributes=[]
    # policies=[]
    form=cloudFileUploadForm()
    doespData=get_object_or_404(DOESPTransaction,pk=id)
    context={'doespData':doespData,'form':form}
    if request.method=="POST":
        form=cloudFileUploadForm(request.POST or None)
        print(request.POST.get('attributes'))
        print(request.POST.get('policies'))
        if form.is_valid():
            attributes=request.POST.get('attributes')
            policies=request.POST.get('policies')
            owner_name=doespData.owner_name
            file_name=doespData.file_name
            enc_file=doespData.enc_file
            pub_key=doespData.pub_key
            downloadCount=0
            status="File Uploaded"
            attributes=attributes
            policies=policies
            print('attr',attributes)
            print('policy',policies)
            form=cloudTransaction(owner_name=owner_name,file_name=file_name,enc_file=enc_file,pub_key=pub_key,status=status,attributes=attributes,policies=policies,downloadCount=downloadCount)

            form.save()
            doespUpdate=DOESPTransaction.objects.filter(id=id).update(status=status)
            print('form sent')
            context={'form':form}
            return HttpResponseRedirect(reverse("owner:cryptography"))
            # return render(request,"owner/uploadCloud.html",context)
        else:
            print("Invalid Form")

lsdss/lsdss/owner/templates/owner/cryptography.html
{% extends 'owner/owner_base.html' %}
{%block title%}Owner | Home{%endblock%}
{%block ownerContent%}
    <div class="container">
        <h1>Cryptography</h1>
        <hr>
        <table class="table">
                <thead>
                  <tr>
                    <th scope="col">File Name</th>
                    <th scope="col">File</th>
                    <th scope="col">Key</th>
                    <th scope="col">Encrypted File</th>
                    <th scope="col">Status</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                    {%for doesp in doespData%}
                        {% if not doespData.status  %}
                            <tr>
                                <td>{{doesp.file_name}}</td>
                                <!-- <td><a href="../{{doesp.owner.owner_file.url}}">{{doesp.owner.owner_file}}</a></td> -->
                                <td><a href="../{{userFile}}">{{userFile}}</a></td>
                                <td>{{doesp.pub_key}}</td>
                                {% if doesp.status == "File Sent to Owner"%}
                                <td><a href="../{{doesp.enc_file}}">{{doesp.enc_file}}</a></td>
                                <th>File Encrypted</th>
                                <td>

                                    <a  href="{%url 'owner:uploadFiletoCloud' doesp.id%}" data-toggle="tooltip" data-placement="top" title="Upload to Cloud" >
                                            <button id="uploadCloudBtn" class="btn btn-primary">
                                                <i class="fas fa-cloud-upload-alt"></i></button>
                                        </a>
                                </td>
                                {% elif doesp.status == "File Uploaded"%}
                                <td><a href="../{{doesp.enc_file}}">{{doesp.enc_file}}</a></td>
                                <td>File Uploaded</td>
                                <td>
                                    None
                                    <!-- <a  href="{%url 'owner:uploadFiletoCloud' doesp.id%}" data-toggle="tooltip" data-placement="top" title="Upload to Cloud" >
                                            <button id="uploadCloudBtn" class="btn btn-success" disabled>
                                                <i class="fas fa-cloud-upload-alt"></i></button>
                                        </a> -->
                                </td>
                                {%else%}
                                <td></td>
                                <th>{{doesp.status}}</th>
                                <td>
                                    <a  href="javascript:{document.getElementById('uploadFileCloud{{doesp.id}}').submit()}" data-toggle="tooltip" data-placement="top" title="Upload to Cloud" >
                                        <button  class="btn btn-primary" disabled>
                                            <i class="fas fa-cloud-upload-alt"></i></button>
                                    </a>
                                {% endif %}
                            </tr>
                        {% endif %}


                        

                      
                  {% endfor %}
                  
                </tbody>
              </table>

              
    </div>
{% endblock %}

lsdss/lsdss/owner/templates/owner/home.html
{% extends 'owner/owner_base.html' %}
{%block title%}Owner | Home{%endblock%}
{%block ownerContent%}

{% endblock %}

lsdss/lsdss/owner/templates/owner/owner_base.html
{% extends 'base.html' %}
{%block title%}{%endblock%}
{%block logo%} Light Secure Data Sharing Scheme - Owner {% endblock %}
{% block navMenu %}

<ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{%url 'owner:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'owner:keyManagement' %}">Key Management</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{%url 'owner:cryptography' %}">Cryptography</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{%url 'owner:uploadFile' %}">Upload File</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{%url 'owner:uploadedFile' %}">Uploaded File</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{%url 'owner:revocationNotification' %}">Revocation Notification</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{%url 'owner:reEncryptedFile' %}">Re-encrypted</a>
        </li>

        <li class="nav-item">
                <a class="nav-link" href="{%url 'accounts:logout' %}">Logout</a>
        </li>
      </ul>

 {% endblock %}
{%block content%}
  {% block ownerContent %}

  {% endblock %}
{% endblock %}

lsdss/lsdss/owner/templates/owner/revocationNotification.html
{% extends 'owner/owner_base.html' %}
{%block title%}Owner | Revocation Notification{%endblock%}
{%block ownerContent%}
<div class="container">
    <h1>Revocating Files</h1>
    <hr>
    <table class="table">
            <thead>
              <tr>
                <th scope="col">File Name</th>
                <th scope="col">File</th>
                <th scope="col">Attributes</th>
                <th scope="col">Policies</th>
                <th scope="col">Total Downloads</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
                {%for ct in ctDatas%}
                  {%if ct.downloadCount >= 3 %}
                  <tr>
                    <td>{{ct.file_name}}</td>
                    <td>{{ct.enc_file}}</td>
                    <td>{{ct.attributes}}</td>
                    <td>{{ct.policies}}</td>
                    <td>{{ct.downloadCount}}</td>
                    {% if ct.status == "File Sent for Re-Encryption"%}
                    <td>{{ct.status}}</td>
                    <td>None</td>
                    {%else%}
                    <td>File is to be revocated</td>
                    <td><button class="btn btn-primary" data-toggle="modal" data-target="#revokeModal">Revoke File</button></td>
                    <!--<td>-->
                    <!--    <a href="javascript:{document.getElementById('revokeFile{{ct.id}}').submit()}" >-->
                    <!--        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#revokeModal" >Revoke</button>-->
                    <!--    </a>-->
                    <!--</td>-->
                    {%endif%}

                  </tr>
                {% endif %}
              {%endfor%}
            </tbody>
          </table>

          <!-- Modal -->
          <div class="modal fade" id="revokeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog-md" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Revoke File</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                    {%for ctData in ctDatas %}

                    <form action="{%url 'owner:revocation' ctData.id %}"  method="post">
                        {%csrf_token%}
                        <strong>File Name</strong>  :  {{ctData.file_name}}<br>
                        <strong>File</strong>       :  {{ctData.enc_file}}<br>
                        <strong>Key</strong>        :  {{ctData.pub_key}}<br>
                        <div class="form-group">
                            <label for="">Update Policy</label>
                            <input type="text" class="form-control" required id="id_policies" name="policies" data-toggle="tooltip" data-placement="right" title="Add multiple policies seperating by comma">
                        </div>

                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Revoke File</button>
                    </div>
                </form>

                {%endfor%}
              </div>
            </div>
          </div>
    </div>
</div>
{%endblock%}

lsdss/lsdss/owner/templates/owner/uploadCloud.html
{% extends 'owner/owner_base.html' %}
{%block title%}Owner | Home{%endblock%}
{%block ownerContent%}
    <div class="container">
        <h1>Cryptography</h1>
        <hr>
        
        <div class="card  mt-4 w-50 mr-auto ml-auto">
                <div class="card-header">
                    <div class="card-title">
                            <h3>Set Attributes and Policy</h3>
                    </div>
                </div>
        <div class="card-body fileUploadCard">
            File Name : {{doespData.file_name}}<br>
            File      : {{doespData.enc_file}}
            <form action="" method="post">
                {%csrf_token%}
                <div class="form-group">
                        <label for="">Attributes</label>
                        <input type="text" class="form-control" required id="id_attributes" name="attributes" data-toggle="tooltip" data-placement="right" title="Add multiple attributes seperating by comma">
                </div>

                <div class="form-group">
                        <label for="">Policy</label>
                        <input type="text" class="form-control" required id="id_policies" name="policies" data-toggle="tooltip" data-placement="right" title="Add multiple policies seperating by comma">
                </div>
                <div class="card-footer">
                    <input type="submit" value="Upload" class="btn btn-primary">
                </div>
            </form>
            </div>
        </div>
              
    </div>
{% endblock %}

lsdss/lsdss/owner/templates/owner/uploadFile.html
{% extends 'owner/owner_base.html' %}
{%block title%}Owner | Home{%endblock%}
{%block ownerContent%}
    <div class="container">
        <div class="card  mt-4 w-50 mr-auto ml-auto">
            <div class="card-header">
                <div class="card-title">
                    <h3>Browse File Here</h3>
                </div>
            </div>
            <div class="card-body fileUploadCard">
                <form action="{%url 'owner:uploadFile' %}" method="POST" enctype="multipart/form-data">
                    {%csrf_token%}
                    <div class=" form-group">
                            <div class="form-group ">
                                <label for="">File Name</label>
                                <input type="text" name="file_name" id="id_file_name" class="form-control">
                            </div>
                    </div>
                    <div class="form-group">
                                <label for="">File</label>
                                <input type="file" name="owner_file" id="id_owner_file" class="form-control">
                    </div>
                    <div class="form-group">
                        <input type="submit" onclick="uploadFileintoSystem()" name="uploadFileBtn" id="uploadFileBtn" value="Upload" class="form-control btn btn-primary">
                    </div>
                </form>
            </div>
        </div>
        <div class="mt-4">
            <h2 class="text-center">Uploaded Files</h2>
            <hr>
            
            <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">File Name</th>
                        <th scope="col">File</th>
                        <th scope="col">Action</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for file in files%}
                    <tr>
                        {% if not file.file_status == "File sent for Encryption" %}
                        <td> {{file.file_name}}</td>
                        
                        <td><a href="../{{file.owner_file.url}}">{{file.owner_file.name}}</a> </td>
                         <td>
                            <a href="{% url 'owner:uploadedFileDelete' file.id %}" data-toggle="tooltip" data-placement="top" title="Delete File" class="btn btn-primary"><i class="fas fa-trash-alt"></i></a>

                            <!-- <a href="javascript:{document.getElementById('deleteFile{{file.id}}').submit()}" data-toggle="tooltip" data-placement="top" title="Delete File">
                                    <button class="btn btn-primary">
                                        <i class="fas fa-trash-alt"></i></button>
                                </a> -->
                            <a href="javascript:{document.getElementById('encryptFile{{file.id}}').submit()}" data-toggle="tooltip" data-placement="top" title="Encrypt File" >
                                    <button class="btn btn-primary">
                                        <i class="fas fa-shield-alt"></i></button>
                                </a>

                    </td>

                    {% endif %}
                    </tr>

                   
                    <!-- FORM:send file to esp for encryption -->
                    <form action="{% url 'owner:sendFiletoEncryption' file.id %}" id="encryptFile{{file.id}}" method="post">
                            {% csrf_token %}
                            <!-- <input type="hidden" name=""> -->
                        </form>
                    {% endfor %}
                    
                    </tbody>
                </table>
                
            </div>
    </div>
{% endblock %}

<!-- {%if not noData%}
                <h2 class="text-center">No Files Uploaded</h2>
            {%else%} -->
            <!-- {% endif %} -->