lsdss/lsdss/accounts/urls.py
from django.urls import path
from accounts import views
app_name ='accounts'
urlpatterns=[
    path('signup',views.signup,name='signup'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
]

lsdss/lsdss/lsdss/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("appAdmin.urls",namespace="adminApp")),
    # path('admin/', include("adminApp.urls",namespace="admin-app")),
    path('owner/', include("owner.urls",namespace="owner")),
    path('user/', include("user.urls",namespace="user")),
    path('tpa/', include("tpa.urls",namespace="tpa")),
    path('encDec/', include("encdec.urls",namespace="encdec")),
    path('accounts/', include("accounts.urls",namespace="accounts")),
    path('cloud/', include("cloud.urls",namespace="cloud")),
] 


if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_URL)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_URL)

lsdss/lsdss/tpa/urls.py
from django.urls import path,include
from tpa import views
app_name="tpa"
urlpatterns=[
    path("",views.Home,name="home"),
    path("ownerkey/",views.ownerKey,name="ownerkey"),
    path("ownerkey/<int:id>",views.generatePubKey,name="generatePubKey"),
    path("ownerkey/<int:id>/sent",views.sendPubKey,name="sendPubKey"),
    path("userkey",views.userKey,name="userkey"),
    path("userkey/<int:id>",views.generateUserPubKey,name="generateUserPubKey"),
    path("userkey/<int:id>/sent",views.sendUserPubKey,name="sendUserPubKey"),
    path("ownerUploadedFiles",views.ownerUploadedFiles,name="ownerUploadedFiles"),
]

lsdss/lsdss/user/urls.py
from django.urls import path,include
from user import views
app_name="user"
urlpatterns=[
    path("",views.Home,name="home"),
    path("viewFiles",views.ViewFiles,name="viewFiles"),
    path("manageKey",views.keyManagement,name="keyManagement"),
    path("cryptography",views.Cryptography,name="cryptography"),
    path("cloudFiles",views.cloudFiles,name="cloudFiles"),
    path("ownerNotification",views.ownerNotification,name="ownerNotification"),
    path("decryptFile/<int:id>",views.sendFiletoDecryption,name="sendFiletoDecryption"),
    path("decryptedFile/",views.decryptedFile,name="decryptedFile"),
    # path("decryptedFile/<int:id>",views.viewDecryptedFile,name="viewDecryptedFile"),
]

lsdss/lsdss/appAdmin/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
import base64

modules=(('Owner','Owner'),('User','User'),('tpa','tpa'),('admin','admin'),('espdsp','espdsp'),('cloud','cloud'))

class register(models.Model):
    user=models.OneToOneField(User,unique=True,on_delete=models.CASCADE)
    mobile = models.CharField(max_length=10)
    city = models.CharField(max_length=15)
    address = models.CharField(max_length=200)
    module = models.CharField(max_length=20, choices=modules)
    strdate = models.DateField(auto_now_add=True)

    def __str__(self):
        return str(self.user)


class DOTATransaction(models.Model):
    owner_name=models.CharField(max_length=30)
    attributes=models.ForeignKey(register,on_delete=models.CASCADE)
    pub_key=models.CharField(max_length=300)
    # _pub_key=models.CharField(max_length=300)

    # def set_data(self, data):
    #     self._pub_key = base64.encodestring(data)

    # def get_data(self):
    #     return base64.decodestring(self._pub_key)

    # pub_key = property(get_data, set_data)
    status=models.CharField(max_length=20)

    def __str__(self):
        return self.owner_name


class ownerFileUpload(models.Model):
    owner_name=models.CharField(max_length=30,null=True,blank=True)
    file_name=models.CharField(max_length=30)
    owner_file=models.FileField(upload_to='media')
    file_status=models.CharField(max_length=30)
    file_upload_date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.file_name

class DOESPTransaction(models.Model):
    # owner=models.ForeignKey(ownerFileUpload,on_delete=models.CASCADE)
    owner_name=models.CharField(max_length=30)
    file_name=models.CharField(max_length=30)
    file_path=models.CharField(max_length=100)
    pub_key=models.CharField(max_length=300)
    status=models.CharField(max_length=30)
    enc_file=models.CharField(max_length=100)
    reEnc_file=models.CharField(max_length=100,blank=True,null=True)

    def __str__(self):
        return self.file_name

class cloudTransaction(models.Model):
    owner_name=models.CharField(max_length=30)
    file_name=models.CharField(max_length=30)
    enc_file=models.CharField(max_length=100)
    pub_key=models.CharField(max_length=300)
    status=models.CharField(max_length=30)
    attributes=models.CharField(max_length=500)
    policies=models.CharField(max_length=500)
    downloadCount=models.PositiveIntegerField()

    def __str__(self):
        return self.file_name

#Owner and User Transaction
class DODUTransaction(models.Model):
    owner_name=models.CharField(max_length=30)
    file_name=models.CharField(max_length=30)
    attributes=models.CharField(max_length=500)
    user_list=models.CharField(max_length=500)
    status=models.CharField(max_length=30)
    
    def __str__(self):
        return self.owner_name

# User Transaction
class DUTATransaction(models.Model):
    user_name=models.CharField(max_length=30)
    attributes=models.ForeignKey(register,on_delete=models.CASCADE)
    pub_key=models.CharField(max_length=300)
    status=models.CharField(max_length=20)

    def __str__(self):
        return self.user_name

class DUCTransaction(models.Model):
    owner_name=models.CharField(max_length=30)
    user_name=models.CharField(max_length=30)
    pub_key=models.CharField(max_length=300)
    attributes=models.CharField(max_length=500)
    status=models.CharField(max_length=30)
    file_name=models.CharField(max_length=30,null=True,blank=True)
    enc_file=models.CharField(max_length=300)
    

    def __str__(self):
        return self.user_name

class DUCDECTransaction(models.Model):
    owner_name=models.CharField(max_length=30)
    user_name=models.CharField(max_length=30)
    pub_key=models.CharField(max_length=300)
    status=models.CharField(max_length=30)
    file_name=models.CharField(max_length=30)
    enc_file=models.CharField(max_length=300)
    dec_file=models.CharField(max_length=300)

    def __str__(self):
        return self.user_name

lsdss/lsdss/user/models.py
from django.db import models

# Create your models here.

lsdss/lsdss/user/views.py
# Create your views here.
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.models import User
from appAdmin.models import register,DUTATransaction,cloudTransaction,DODUTransaction,DUCTransaction,DUCDECTransaction
from appAdmin.forms import DUCTransactionForm
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse

# Create your views here.
def Home(request):
    username=request.session['username']
    request.session['username']=username

    context={}
    return render(request,"user/home.html",context)


def keyManagement(request):
    username=request.session['username']
    print(username)

    user_attributes_list=[]
    users=User.objects.filter(username=username)
    for user in users:
        user_attributes=register.objects.filter(user=user.id)
        for usr in user_attributes:
            user_attributes_list.append(usr.user.username)
            user_attributes_list.append(usr.user.email)
            user_attributes_list.append(usr.mobile)
        #     print(usr.user.username,usr.user.first_name,usr.user.last_name,usr.mobile)
            print("uattr-",user_attributes_list)
    status="No Key Requested"
    pub_Key=""
    duta_trans=DUTATransaction.objects.filter(user_name=username)
    if duta_trans is not None:
        for duta in duta_trans:
            status=duta.status
            pub_Key=duta.pub_key

    context={'user_attributes':user_attributes,'status':status,'pub_Key':pub_Key}
    # return render(request,"owner/managekey.html",context)
    if request.method=='POST':
        # dotaTransaction=DOTATransaction()
        status="Key Requested"
        user_name=username
        attributes=user_attributes_list
        status=status
        pub_Key=pub_Key
        duta=DUTATransaction(user_name=username,attributes=register.objects.get(user=user.id),status=status,pub_key=pub_Key)
        duta.save()
        duta_trans=DUTATransaction.objects.filter(user_name=user_name)
        for duta in duta_trans:
            status=duta.status
            pub_Key=duta.pub_key
            print('duta--',duta.status)
        print("attr-",attributes)
        print('sta-',status)
        context={'duta_trans':duta_trans,'user_attributes':user_attributes,'status':status,'pub_Key':pub_Key}
        return render(request,"user/managekey.html",context)
    else:
        status=status
        return render(request,"user/managekey.html",context)
    # return render(request,"user/managekey.html",context)

def Cryptography(request):
    username=request.session['username']
    if request.method=='POST':
        print('i m in post')
        ducdatas=DUCTransaction.objects.filter(user_name=username)
        for ducdata in ducdatas:
            file_name = ducdata.file_name
        print(file_name)
        context={}
        return render(request,"user/cryptography.html",context)
    else:
        print('i m in get')
        context={}
        return render(request,"user/cryptography.html",context)


def ownerNotification(request):
    username=request.session['username']
    print(username)
    form=DUCTransactionForm()
    doduDatas=DODUTransaction.objects.all()
    dutaDatas= DUTATransaction.objects.filter(user_name=username)

    if request.method=='POST':
        print('I m in post')
        doduDatas=DODUTransaction.objects.all()
        dutaDatas= DUTATransaction.objects.filter(user_name=username)
        attributeValue=request.POST.get('attributes')
        status="File Requested to Cloud"
        print('duta',dutaDatas)
        print('do--',doduDatas)
        for dodu in doduDatas:
            file_name = dodu.file_name
            owner_name=dodu.owner_name
        for dutaData in dutaDatas:
            user_name=dutaData.user_name
            pub_key=dutaData.pub_key
            print('user_name',dutaData.user_name)
        form=DUCTransactionForm(request.POST or None)
        if form.is_valid():
            duc=DUCTransaction(owner_name=owner_name,user_name=user_name,pub_key=pub_key,attributes=attributeValue,status=status,file_name=file_name)
            duc.save()
            print('Requested to Cloud')
            context={'username':username,'form':form}
            return render(request,'user/home.html',context)
        else:
            print('I m invalid')
            context={'username':username,'doduDatas':doduDatas,'dutaDatas':dutaDatas,'form':form}
            return render(request,'user/ownernotification.html',context)
    else:
        print('I m in get')
        context={'username':username,'doduDatas':doduDatas,'dutaDatas':dutaDatas,'form':form}
        return render(request,'user/ownernotification.html',context)

def ViewFiles(request):
    username=request.session['username']
    ducfiles=DUCTransaction.objects.filter(user_name=username)
    # ducfiles=DUCTransaction.objects.all()
    context={'ducfiles':ducfiles}
    return render(request,"user/viewFile.html",context)

    # ducdecData=DUCDECTransaction.objects.all()
    # for ducdec in ducdecData:
    #     status=ducdec.status
    #     dec_file=ducdec.dec_file
    #     # dec_file=ducdec.dec_file
    # # print(dec_file)
    # ducfiles = DUCTransaction.objects.all()
    # # context={'ducfiles':ducfiles,'status':status}
    # # username=request.session['username']
    # if request.method=='POST':
    #     ducdatas=DUCTransaction.objects.filter(user_name=username)
    #     for ducdata in ducdatas:
    #         file_name = ducdata.file_name
    #     print(file_name)
    #     context={'ducfiles':ducfiles}
    #     # context={'ducdecData':ducdecData}
    #     # return render(request,"user/viewFile.html",context)
    #     return HttpResponseRedirect(reverse('user:viewFiles'))
    # else:
    #     context={'ducfiles':ducfiles,'status':status}
    #     return render(request,"user/viewFile.html",context)
    #     # if dec_file is None:
    #     # else:
    #     #     context={'ducfiles':ducfiles,'status':status,'dec_file':dec_file}
    #     #     return render(request,"user/viewFile.html",context)


def sendFiletoDecryption(request,id):
    ducData = get_object_or_404(DUCTransaction,pk=id)
    owner_name=ducData.owner_name
    user_name=ducData.user_name
    pub_key=ducData.pub_key
    file_name=ducData.file_name
    enc_file=ducData.enc_file
    status="File Sent for Decryption"
    ducdec=DUCDECTransaction(owner_name=owner_name,user_name=user_name,pub_key=pub_key,file_name=file_name,enc_file=enc_file,status=status)
    ducdec.save()
    ducData=get_object_or_404(DUCTransaction,pk=id)
    ducData=DUCTransaction.objects.filter(pk=id).update(status=status)
    print("File sent for decryption")
    context={}
    # return render(request,"user/viewFile.html",context)
    return HttpResponseRedirect(reverse('user:viewFiles'))

def decryptedFile(request):
    username=request.session['username']
    # ducfiles=DUCTransaction.objects.filter(user_name=username)
    dudecs=DUCDECTransaction.objects.filter(user_name=username)
    print(dudecs)
    context={'dudecs':dudecs}
    return render(request,'user/decryptedFile.html',context)

# def viewDecryptedFile(request,id):
#     dudecs=get_object_or_404(DUCDECTransaction,pk=id)
#     print(dudecs.dec_file)
#     context={}
#     return HttpResponseRedirect(reverse('user:decryptedFile'))


def cloudFiles(request):
    ducFiles=cloudTransaction.objects.all()
    context={'ducFiles':ducFiles}
    return render(request,'user/cloudFiles.html',context)

lsdss/lsdss/user/templates/user/cloudFiles.html
{% extends 'user/user_base.html' %}
{%block title%}User | Cloud Files{%endblock%}
{%block userContent%}
<div class="container">
        <h2>Cloud Files</h2>
        <table class="table col-md-6">
            <thead>
              <tr>
                <th scope="col">Owner Name</th>
                <th scope="col">File Name</th>
                <!-- <th scope="col">File</th> -->
              </tr>
            </thead>
            <tbody>
                {%for ducFile in ducFiles%}
                <tr>
                    <td>{{ducFile.owner_name}}</td>
                    <td>{{ducFile.file_name}}</td>
                    <!-- <td>{{ducFile.}}</td> -->
                </tr>
                {%endfor%}
            </tbody>

            </table>
{%endblock%}

lsdss/lsdss/user/templates/user/cryptography.html
{% extends 'user/user_base.html' %}
{%block title%}User | Home{%endblock%}
{%block userContent%}

{% endblock %}

lsdss/lsdss/user/templates/user/decryptedFile.html
{% extends 'user/user_base.html' %}
{%block title%}User | Files{%endblock%}
{%block userContent%}
<div class="container mt-2">
<h2>Decrypted Files</h2>
<hr>

<table class="table">
    <thead>
        <th>File Name</th>
        <th>Decrypted File</th>
        <th>File Status</th>
        <th>Action</th>
    </thead>
        <tbody>
            {%for dudec in dudecs%}
            {%if dudec.status == 'Decrypted File Sent' %}
            <tr>
                <td>{{dudec.file_name}}</td>
                <td>{{dudec.dec_file}}</td>
                {%if dudec.status == 'Decrypted File Sent' %}
                <td>File Recieved</td>
                {%else%}
                <td>{{dudec.status}}</td>
                {%endif%}
                <td> <a  href="../../{{dudec.dec_file}}"><button class="btn btn-primary" > View File</button> </a></td>
                <!-- <td><a  href="javascript:{document.getElementById('viewDecryptedFile{{dudec.id}}').submit()}"><button class="btn btn-primary"> View </button></a></td> -->
            </tr>

            {%endif%}
            {%endfor%}
        </tbody>
</table>








{% endblock %}

lsdss/lsdss/user/templates/user/home.html
{% extends 'user/user_base.html' %}
{%block title%}User | Home{%endblock%}
{%block userContent%}

{% endblock %}

lsdss/lsdss/user/templates/user/managekey.html
{% extends 'user/user_base.html' %}
{%block title%}User | Key Manage{%endblock%}
{%block userContent%}
<div class="container">
    <h1 class="center">Key Management</h1>
    <hr>
    <table class="table thead-dark mt-4">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Attributes</th>
            <th scope="col">Status</th>
            <th scope="col">Key</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            {% for usr in user_attributes %}
            <td >{{usr.user.username}}</td>
            <td>{{usr.user.username}},{{usr.user.email}},{{usr.mobile}}</td>
            <!-- <td>status</td> -->
            {% if status == "Key Sent to User" %}
            <td id="key_status">Key Recieved</td>
            {%else%}
            <td>{{status}}</td>
            {% endif %}
            {% if status == "Key Sent to User" %}
            <td>{{pub_Key}}</td>
            {%else%}
            <td></td>
            {% endif %}
            <td>
                <form action="{%url 'user:keyManagement'%}" id="requestKeyForm" method="POST">
                    {%csrf_token%}
                    {% if status == "Key Requested" %}
                    <input type="submit" class="btn btn-success" id="requestKeyBtn" value="Done" disabled>
                    {% elif status == "Key Generated" or status == "Key Sent to User" %}
                    <!-- <input type="submit" class="btn btn-success" id="requestKeyBtn" value="Done" disabled> -->
                    None
                    {%else%}
                    <input type="submit" class="btn btn-primary" id="requestKeyBtn" value="Request Key" onclick="changeButton()">
                    {% endif %}
                    <!-- <button type="submit" class="btn btn-primary" id="requestKeyBtn">Request Key</button> -->
                </form>
            </td>
            {% endfor %}
          </tr>
          
        </tbody>
      </table>
</div>
{% endblock %}

lsdss/lsdss/user/templates/user/ownernotification.html
{% extends 'user/user_base.html' %}
{%block title%}User | Owner Notification{%endblock%}
{%block userContent%}
    <div class="container mt-2">
        <h2>Owner Notification</h2>
        <hr>
        <table class="table">
            <thead>
                <th>Owner Name</th>
                <th>File Name</th>
                <th>Attributes</th>
                <th>Action</th>
                <th>Status</th>
            </thead>
                {%for dodudata in doduDatas%}
                    {%if username in dodudata.user_list%}
                    <tbody>
                        <tr>
                            <td>{{dodudata.owner_name}}</td>
                            <td>{{dodudata.file_name}}</td>
                            <td>{{dodudata.attributes}}</td>
                            <td><button class="btn btn-primary" data-toggle="modal" data-target="#requestModal">Request</button></td>
                            
                        </tr>
                    {%endif%}
                {% endfor %}
                    </tbody>
        </table>
        
        <!-- Modal -->
        <div class="modal fade" id="requestModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Request Data</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <form action="" method="POST">
                       {% csrf_token %}
                      <div class="modal-body">
                            {%for dutaData in dutaDatas%}
                            <table>
                              <tr>
                                <td>User : </td>
                                <td>{{dutaData.user_name}}</td>
                              </tr>
                              <tr>
                                <td>Key : </td>
                                <td>{{dutaData.pub_key}}</td>
                              </tr>
                            </table>
                            
                            
                            {%endfor%}
                            <div class="form-group">
                                <label for="policies">Attributes</label>
                                <input type="text" class="form-control" required id="id_attributes" name="attributes" data-toggle="tooltip" data-placement="right" title="Add multiple attributes seperating by comma">
                              </div>
                        
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Request</button>
                      </div>
                    </form>
                  </div>
                </div>    
            </div>    
        </div>        
{% endblock %}

lsdss/lsdss/user/templates/user/user_base.html
{% extends 'base.html' %}
{%block title%}{%endblock%}
{% block logo %} Light Secure Data Sharing Scheme - User {% endblock %}
{% block navMenu %}

<ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{%url 'user:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        
        <li class="nav-item">
            <a class="nav-link" href="{%url 'user:keyManagement' %}">Key Management</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{%url 'user:cryptography' %}">Cryptography</a>
        </li>
        <li class="nav-item">
                <a class="nav-link" href="{%url 'user:cloudFiles' %}">Cloud Files</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{%url 'user:ownerNotification' %}">Owner Notification</a>
        </li>
        <li class="nav-item">
                <a class="nav-link" href="{%url 'user:viewFiles' %}">View Files</a>
        </li>
        <li class="nav-item">
                <a class="nav-link" href="{%url 'user:decryptedFile' %}">Decrypted Files</a>
        </li>
        <li class="nav-item">
                <a class="nav-link" href="{%url 'accounts:logout' %}">Logout</a>
        </li>
      </ul>

 {% endblock %}

 {%block content%}
{%block userContent%}

{% endblock %}
{% endblock %}

lsdss/lsdss/user/templates/user/viewFile.html
{% extends 'user/user_base.html' %}
{%block title%}User | Files{%endblock%}
{%block userContent%}
<div class="container mt-2">
<h2>View Files</h2>
<hr>
<table class="table">
    <thead>
        <th>File Name</th>
        <th>Enc File</th>
        {% if status == 'File Sent' %}
        <th>Dec File</th>
        {%endif%}
        <th>status</th>
        <th>Action</th>
        <tbody>
            
            {% for ducfile in ducfiles %}
            <tr>
                <td>{{ducfile.file_name}}</td>
                <td>{{ducfile.enc_file}}</td>
                {% if ducfile.status == 'File Sent to User' %}
                <td>Encrypted File Received </td>
                {% elif ducfile.status == 'Decrypted File Sent' %}
                <td>Decrypted File Received </td>
                {%else%}
                <td>{{ducfile.status}}</td>
                {% endif %}

                

                {% if  ducfile.status == 'File Sent to User' %}
                <td>
                    <a  href="javascript:{document.getElementById('decryptFile{{ducfile.id}}').submit()}"><button class="btn btn-primary"> Decrypt </button> </a>

                <a  href="../{{ducfile.enc_file}}"><button class="btn btn-primary" > View File</button> </a>
            </td>
                {% elif  ducfile.status == 'Not Verified' %}
                <td>
                None
            </td>
                {% else %}
                <td>None</td>
                <!-- <td>
                    <a  href="../{{ducfile.enc_file}}"><button class="btn btn-primary" >Encrypted File </button></a>
                    <a  href="javascript:{document.getElementById('decryptFile{{ducfile.id}}').submit()}"><button class="btn btn-primary"> Decrypt </button></a>
                </td> -->

               
                {% endif %}
            </tr>
            <!-- FORM:send file to esp for decryption -->
            <form action="{% url 'user:sendFiletoDecryption' ducfile.id %}" id="decryptFile{{ducfile.id}}" method="post">
                {% csrf_token %}
                <!-- <input type="hidden" name=""> -->
            </form>
            {% endfor %}
        </tbody>
    </thead>
</table>
     
{% endblock %}