lsdss/lsdss/accounts/urls.py
from django.urls import path
from accounts import views
app_name ='accounts'
urlpatterns=[
    path('signup',views.signup,name='signup'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
]

lsdss/lsdss/encdec/urls.py
from django.urls import path,include
from encdec import views
app_name="encdec"
urlpatterns=[
    path("",views.Home,name="home"),
    path("encryption",views.encryption,name="encryption"),
    path("encryption/<int:id>",views.encryptFile,name="encryptFile"),
    path("encryption/File:<int:id>",views.sendEncryptedFiles,name="sendEncryptedFiles"),
    path("decryption",views.decryption,name="decryption"),
    path("decryption/<int:id>",views.decryptFile,name="decryptFile"),
    path("decryption/<int:id>/sent",views.sendDecryptedFile,name="sendDecryptedFile"),

    path("reEncryption",views.reEncryption,name="reEncryption"),
    path("reEncryption/<int:id>",views.reEncryptFile,name="reEncryptFile"),
    path("reEncryption/File:<int:id>",views.sendReEncryptedFiles,name="sendReEncryptedFiles"),
    
    
]

lsdss/lsdss/lsdss/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("appAdmin.urls",namespace="adminApp")),
    # path('admin/', include("adminApp.urls",namespace="admin-app")),
    path('owner/', include("owner.urls",namespace="owner")),
    path('user/', include("user.urls",namespace="user")),
    path('tpa/', include("tpa.urls",namespace="tpa")),
    path('encDec/', include("encdec.urls",namespace="encdec")),
    path('accounts/', include("accounts.urls",namespace="accounts")),
    path('cloud/', include("cloud.urls",namespace="cloud")),
] 


if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_URL)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_URL)

lsdss/lsdss/tpa/urls.py
from django.urls import path,include
from tpa import views
app_name="tpa"
urlpatterns=[
    path("",views.Home,name="home"),
    path("ownerkey/",views.ownerKey,name="ownerkey"),
    path("ownerkey/<int:id>",views.generatePubKey,name="generatePubKey"),
    path("ownerkey/<int:id>/sent",views.sendPubKey,name="sendPubKey"),
    path("userkey",views.userKey,name="userkey"),
    path("userkey/<int:id>",views.generateUserPubKey,name="generateUserPubKey"),
    path("userkey/<int:id>/sent",views.sendUserPubKey,name="sendUserPubKey"),
    path("ownerUploadedFiles",views.ownerUploadedFiles,name="ownerUploadedFiles"),
]

lsdss/lsdss/encdec/models.py
from django.db import models

# Create your models here.

lsdss/lsdss/encdec/views.py
from django.shortcuts import render,get_object_or_404
from appAdmin.models import DOESPTransaction,DUCDECTransaction,DUCTransaction
from django.http import HttpResponseRedirect
from django.urls import reverse
import base64
import hashlib
import os,random,struct,sys
from cryptography.fernet import Fernet
from django.core.files.storage import FileSystemStorage


# Create your views here.
def Home(request):
    context={}
    return render(request,"enc_dec/home.html",context)

def encryption(request):
    doespData=DOESPTransaction.objects.all()
    context={'doespData':doespData}
    return render(request,"enc_dec/encryption.html",context)

def encryptFile(request,id):
    if request.method=='POST':
        doespData=get_object_or_404(DOESPTransaction,pk=id)
        print(doespData.file_name)
        print(doespData.file_path)
        input_file='/home/lsdss/lsdss/'+ doespData.file_path
        i1=input_file.split('/')
        i1=str(i1[5])
        i2=i1.split('.')
        # print(i[2])
        key = Fernet.generate_key()
        print(input_file)
        print(key)
        with open(input_file, 'rb') as f:
            data = f.read()
        print(data)
        fernet = Fernet(key)
        encrypted = fernet.encrypt(data)
        print('enc--',encrypted)
        output_file=(str(i2[0])+'.encrypted')
        print(output_file)
        with open(output_file, 'wb+') as of:
            of.write(encrypted)

            fs = FileSystemStorage()
            filename = fs.save(output_file, of)
            encrypted_file_url = fs.url(filename)
        print(encrypted_file_url)


        status="File Encrypted"
        enc_file=encrypted_file_url
        doespUpdate=DOESPTransaction.objects.filter(id=id).update(status=status,enc_file=enc_file)
        doespData=get_object_or_404(DOESPTransaction,pk=id)
        context={'doespData':doespData}
        return HttpResponseRedirect(reverse("encdec:encryption"))
    else:
        return HttpResponseRedirect(reverse("encdec:encryption"))
    # doespData=get_object_or_404(DOESPTransaction,id=id)
    # owner_key=doespData.pub_key
    # print(owner_key)
    # key1= owner_key.encode("utf8")
    # print(len(key1))
    # key= '0123456789abcdef'
    # in_filename = doespData.file_path
    # out_filename = None
    # chunksize = 64*1024
    # aesEnc=AESEncryption(key.encode("utf8"),in_filename,out_filename,chunksize)
    # context={}
    # return HttpResponseRedirect(reverse("encdec:encryption"))
    # return render(request,"enc_dec/encryption.html",context)

def sendEncryptedFiles(request,id):
    if request.method=='POST':
        doespData=get_object_or_404(DOESPTransaction,pk=id)
        print('status-->',doespData.status)
        if doespData.status=="File Encrypted":
            status="File Sent to Owner"

        doespUpdate=DOESPTransaction.objects.filter(id=id).update(status=status)
        doespData=get_object_or_404(DOESPTransaction,pk=id)
        context={'doespData':doespData}
        return HttpResponseRedirect(reverse("encdec:encryption"))
    else:
        return HttpResponseRedirect(reverse("encdec:encryption"))


def decryption(request):
    ducdecData=DUCDECTransaction.objects.all()
    context={'ducdecData':ducdecData}
    return render(request,"enc_dec/decryption.html",context)
    # return HttpResponseRedirect(reverse("encdec:decryption"))

def decryptFile(request,id):
    print(id)
    ducdecData=get_object_or_404(DUCDECTransaction,pk=id)
    print(ducdecData.id)
    encFile=ducdecData.enc_file
    print(encFile)
    doesps=DOESPTransaction.objects.filter(enc_file=encFile)
    for doesp in doesps:
        decFile= doesp.file_path

    print(doesp.file_path)
    d1=decFile.split('/')
    vl = '/'
    # decFile1=d1
    decFile1=d1[1] + vl +d1[2]
    # print(decFile)
    status="File Decrypted"
    ducdecuData=DUCDECTransaction.objects.filter(pk=id).update(dec_file=decFile1,status=status)
    ducdatas=DUCTransaction.objects.filter(pk=id).update(status=status)
    context={}
    # return render(request,"enc_dec/decryption.html",context)
    return HttpResponseRedirect(reverse("encdec:decryption"))

def sendDecryptedFile(request,id):
    print("Send me")
    ducdecData=get_object_or_404(DUCDECTransaction,pk=id)
    print(ducdecData)
    status="Decrypted File Sent"
    ducdecuData=DUCDECTransaction.objects.filter(pk=id).update(status=status)
    ducdatas=DUCTransaction.objects.filter(pk=id).update(status=status)
    print(ducdecData)
    context={}
    # return render(request,"enc_dec/decryption.html",context)
    return HttpResponseRedirect(reverse("encdec:decryption"))


def AESEncryption(key,in_filename,out_filename,chunksize):
    if not out_filename:
        out_filename = in_filename + '.enc'
    iv=(16 * '\x00').encode("utf8")
    # iv = ''.join(chr(random.randint(0, 0xFF)) for i in range(12)).encode("utf8")
    print('iv---',len(iv))
    encryptor = AES.new(key, AES.MODE_CBC, iv)
    filesize = os.path.getsize(in_filename)

    with open(in_filename, 'rb') as infile:
        with open(out_filename, 'wb') as outfile:
            outfile.write(struct.pack('<Q', filesize))
            outfile.write(iv)

            while True:
                chunk = infile.read(chunksize)
                if len(chunk) == 0:
                    break
                elif len(chunk) % 16 != 0:
                    chunk += bytes(16 - len(chunk) % 16)

                outfile.write(encryptor.encrypt(chunk))

 # key = '0123456789abcdef'
    # IV = 16 * '\x00'           # Initialization vector: discussed later
    # mode = AES.MODE_CBC
    # encryptor = AES.new(key.encode("utf8"), mode, IV=IV.encode("utf8"))

    # text = 'j' * 64 + 'i' * 128
    # ciphertext = encryptor.encrypt(text.encode("utf8"))
    # print(key)
    # print('text-------',text)
    # print('ciphertext-------',ciphertext)


# Revocation
# Re encryption

def reEncryption(request):
    # status='File Sent for Re-Encryption'
    # doespData=DOESPTransaction.objects.filter(status=status)
    doespData=DOESPTransaction.objects.all()
    context={'doespData':doespData}
    return render(request,'enc_dec/reEncryption.html',context)

def reEncryptFile(request,id):
    if request.method=='POST':
        doespData=get_object_or_404(DOESPTransaction,pk=id)
        print(doespData.file_name)
        print(doespData.enc_file)
        # input_file=doespData.enc_file
        # inp=input_file.split('/')
        # i1=str(inp[2])
        input_file='/home/lsdss/lsdss/'+ doespData.enc_file
        i1=input_file.split('/')
        i1=str(i1[5])
        i2=i1.split('.')
        # print(i[2])
        key = Fernet.generate_key()
        print(input_file)
        print(key)
        with open(input_file, 'rb') as f:
            data = f.read()
        print(data)
        fernet = Fernet(key)
        encrypted = fernet.encrypt(data)
        print('enc--',encrypted)
        output_file=('(re)'+str(i2[0])+'.encrypted')
        print(output_file)
        with open(output_file, 'wb+') as of:
            of.write(encrypted)

            fs = FileSystemStorage()
            filename = fs.save(output_file, of)
            encrypted_file_url = fs.url(filename)
        print(encrypted_file_url)


        status="File Re-encrypted"
        reEnc_file=encrypted_file_url
        doespUpdate=DOESPTransaction.objects.filter(id=id).update(status=status,reEnc_file=reEnc_file)
        doespData=get_object_or_404(DOESPTransaction,pk=id)
        context={'doespData':doespData}
        return HttpResponseRedirect(reverse("encdec:reEncryption"))
    else:
        return HttpResponseRedirect(reverse("encdec:reEncryption"))

def sendReEncryptedFiles(request,id):
    if request.method=='POST':
        doespData=get_object_or_404(DOESPTransaction,pk=id)
        print('status-->',doespData.status)
        if doespData.status=="File Re-encrypted":
            status="Re-Encrypted File Sent to Owner"

        doespUpdate=DOESPTransaction.objects.filter(id=id).update(status=status)
        doespData=get_object_or_404(DOESPTransaction,pk=id)
        context={'doespData':doespData}
        return HttpResponseRedirect(reverse("encdec:reEncryption"))
    else:
        return HttpResponseRedirect(reverse("encdec:ReEncryption"))

lsdss/lsdss/encdec/templates/enc_dec/decryption.html
{% extends 'enc_dec/enc_dec_base.html' %}
{%block title%}Cryptography | Decryption {%endblock%}
{%block encdecContent%}
<h2>Files for Decryption</h2>

<hr>
<table class="table">
    <thead>
        <th>User Name</th>
        <th>Key</th>
        <th>File Name</th>
        <th>Enc File</th>
        <th>Dec File</th>
        <th>Status</th>
        <th>Action</th>
        <tbody>
            {% for ducdec in ducdecData%}
            <tr>
                <td>{{ducdec.user_name}}</td>
                <td>{{ducdec.pub_key}}</td>
                <td>{{ducdec.file_name}}</td>
                <td>{{ducdec.enc_file}}</td>
                <td>{{ducdec.dec_file}}</td>
                {% if ducdec.status == 'File Sent for Decryption' %}
                <td>File Recieved for Decryption</td>
                {%else%}
                <td>{{ducdec.status}}</td>
                {%endif%}
                <td>
                    {%if ducdec.status == 'File Decrypted'%}
                    <!-- <a  href="javascript:{document.getElementById('decryptFile{{ducdec.id}}').submit()}"><button class="btn btn-success" disabled>Decrypted</button> </a> -->
                    <a  href="javascript:{document.getElementById('sendDecryptedFile{{ducdec.id}}').submit()}"><button class="btn btn-primary" >Send</button></a>

                    {% elif ducdec.status == 'Decrypted File Sent' %}
                    None
                    <!-- <a  href="javascript:{document.getElementById('decryptFile{{ducdec.id}}').submit()}"><button class="btn btn-success" disabled>Decrypted</button> </a>
                    <a  href="javascript:{document.getElementById('sendDecryptedFile{{ducdec.id}}').submit()}"><button class="btn btn-success" disabled>Sent</button></a> -->

                    {% elif ducdec.status == 'File Sent for Decryption' %}
                    <a  href="javascript:{document.getElementById('decryptFile{{ducdec.id}}').submit()}"><button class="btn btn-primary" >Decrypt</button> </a>
                    <!-- <a  href="javascript:{document.getElementById('sendDecryptedFile{{ducdec.id}}').submit()}"><button class="btn btn-success" disabled>Sent</button></a> -->
                    {% else %}
                    <a  href="javascript:{document.getElementById('decryptFile{{ducdec.id}}').submit()}"><button class="btn btn-primary" >Decrypt</button> </a>
                    <a  href="javascript:{document.getElementById('sendDecryptedFile{{ducdec.id}}').submit()}"><button class="btn btn-primary" disabled>Send</button></a></a>
                    {% endif %}

                </td>
            </tr>

            <!-- FORM:Decrypt File -->
            <form action="{% url 'encdec:decryptFile' ducdec.id %}" id="decryptFile{{ducdec.id}}" method="post">
                    {% csrf_token %}
                    <!-- <input type="hidden" name=""> -->
                </form>

            <form action="{% url 'encdec:sendDecryptedFile' ducdec.id %}" id="sendDecryptedFile{{ducdec.id}}" method="post">
                        {% csrf_token %}
                        <!-- <input type="hidden" name=""> -->
                    </form>
            {% endfor %}
        </tbody>
    </thead>
</table>

{% endblock %}

lsdss/lsdss/encdec/templates/enc_dec/enc_dec_base.html
{% extends 'base.html' %}
{%block title%}{%endblock%}
{%block logo%} Light Secure Data Sharing Scheme -Cryptography {% endblock %}
{% block navMenu %}

<ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{%url 'encdec:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'encdec:encryption' %}">Encryption</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{%url 'encdec:decryption' %}">Decryption</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{%url 'encdec:reEncryption' %}">Re-encryption</a>
          </li>
        <li class="nav-item">
            <a class="nav-link" href="{%url 'accounts:logout' %}">Logout</a>
        </li>
      </ul>

 {% endblock %}

{%block content %}
  {%block encdecContent%}

  {% endblock %}
{%endblock%}

lsdss/lsdss/encdec/templates/enc_dec/encryption.html
{% extends 'enc_dec/enc_dec_base.html' %}
{%block title%}Cryptography | Home{%endblock%}
{%block encdecContent%}
    <div class="container">
        <div class="h1">Files for Encryption</div>
        <hr>
        <table class="table ">
            <thead>
              <tr>
                <th scope="col">Owner Name</th>
                <th scope="col">Key</th>
                <th scope="col">File Name</th>
                <th scope="col">File</th>
                <th scope="col">Encrypted File</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
                {%for doesp in doespData %}
              <tr>
                <td>{{doesp.owner_name}}</td>
                <td>{{doesp.pub_key}}</td>
                <td>{{doesp.file_name}}</td>
                <td><a href="../{{doesp.file_path}}">{{doesp.file_path}}</a></td>
                <td><a href="../{{doesp.enc_file}}">{{doesp.enc_file}}</a></td>
                {% if doesp.status == "File sent for Encryption"%}
                <td>File to be Encrypted</td>
                {%else%}
                <td>{{doesp.status}}</td>
                {% endif %}
                <td>
                  {%if doesp.status == 'File Encrypted' %}
                  <!-- <a href="javascript:{document.getElementById('encryptOwnerFile{{doesp.id}}').submit()}" >
                      <button type="submit" class="btn btn-success" name="encryptFileBtn" id="encryptFileBtn" disabled>Encrypted</button>
                      </a> -->

                      <a href="javascript:{document.getElementById('sendEncryptedFile{{doesp.id}}').submit()}" >
                      <button type="submit" class="btn btn-primary" name="sendEncryptedFileBtn" id="sendEncryptedFileBtn" >Send</button>
                    </a>
                  {%elif doesp.status == 'File Sent to Owner' %}
                  None
                  <!-- <a href="javascript:{document.getElementById('encryptOwnerFile{{doesp.id}}').submit()}" >
                      <button type="submit" class="btn btn-success" name="encryptFileBtn" id="encryptFileBtn" disabled>Encrypt</button>
                      </a>
                      <br>
                      <a href="javascript:{document.getElementById('sendEncryptedFile{{doesp.id}}').submit()}" >
                      <button type="submit" class="btn btn-success" name="sendEncryptedFileBtn" id="sendEncryptedFileBtn" disabled>Sent</button>
                    </a> -->
                    {%elif doesp.status == 'File Uploaded' %}
                    None
                  <!-- <a href="javascript:{document.getElementById('encryptOwnerFile{{doesp.id}}').submit()}" >
                      <button type="submit" class="btn btn-success" name="encryptFileBtn" id="encryptFileBtn" disabled>Encrypt</button>
                      </a>
                      <br>
                      <a href="javascript:{document.getElementById('sendEncryptedFile{{doesp.id}}').submit()}" >
                      <button type="submit" class="btn btn-success" name="sendEncryptedFileBtn" id="sendEncryptedFileBtn" disabled>Sent</button>
                    </a> -->
                  {%else%}
                    <a href="javascript:{document.getElementById('encryptOwnerFile{{doesp.id}}').submit()}" >
                    <button type="submit" class="btn btn-primary" name="encryptFileBtn" id="encryptFileBtn">Encrypt</button>
                    </a>
                    <!-- <a href="javascript:{document.getElementById('sendEncryptedFile{{doesp.id}}').submit()}" >
                    <button type="submit" class="btn btn-primary" name="sendEncryptedFileBtn" id="sendEncryptedFileBtn">Send</button> -->
                  </a>
                </td>
                {% endif %}
              </tr>

              <!-- FORM:Encrypt file -->
              <form action="{% url 'encdec:encryptFile' doesp.id %}" id="encryptOwnerFile{{doesp.id}}" method="post">
                    {% csrf_token %}
                    <!-- <input type="hidden" name=""> -->
                </form>

                <!-- Send encrypted file -->
                <form action="{% url 'encdec:sendEncryptedFiles' doesp.id %}" id="sendEncryptedFile{{doesp.id}}" method="post">
                  {% csrf_token %}
                  <!-- <input type="hidden" name=""> -->
              </form>
              {% endfor %}
              
            </tbody>
          </table>
    </div>
{% endblock %}

lsdss/lsdss/encdec/templates/enc_dec/home.html
{% extends 'enc_dec/enc_dec_base.html' %}
{%block title%}Cryptography | Home{%endblock%}
{%block encdecContent%}

{% endblock %}

lsdss/lsdss/encdec/templates/enc_dec/reEncryption.html
{% extends 'enc_dec/enc_dec_base.html' %}
{%block title%}Cryptography | Home{%endblock%}
{%block encdecContent%}
    <div class="container-fluid">
        <div class="h1">Files for Re-Encryption</div>
        <hr>
        <table class="table ">
            <thead>
              <tr>
                <th scope="col">Owner Name</th>
                <th scope="col">Key</th>
                <th scope="col">File Name</th>
                <th scope="col">File</th>
                <th scope="col">Encrypted File</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
                {%for doesp in doespData %}
              <tr>
                <td>{{doesp.owner_name}}</td>
                <td>{{doesp.pub_key}}</td>
                <td>{{doesp.file_name}}</td>
                <td><a href="../{{doesp.enc_file}}">{{doesp.enc_file}}</a></td>
                {%if doesp.status == 'File Re-encrypted' %}
                <td><a href="../{{doesp.reEnc_file}}">{{doesp.reEnc_file}}</a></td>
                {%elif doesp.status == 'Re-Encrypted File Sent to Owner' %}
                <td><a href="../{{doesp.reEnc_file}}">{{doesp.reEnc_file}}</a></td>
                {%else%}
                <td>None</td>
                {%endif%}
                {% if doesp.status == "File Sent for Re-Encryption"%}
                <td>File Sent for Re-Encryption</td>
                {%else%}
                <td>{{doesp.status}}</td>
                {% endif %}
                <td>
                  {%if doesp.status == 'File Re-encrypted' %}
                  <!-- <a href="javascript:{document.getElementById('encryptOwnerFile{{doesp.id}}').submit()}" >
                      <button type="submit" class="btn btn-success" name="encryptFileBtn" id="encryptFileBtn" disabled>Encrypted</button>
                      </a> -->

                      <a href="javascript:{document.getElementById('sendEncryptedFile{{doesp.id}}').submit()}" >
                      <button type="submit" class="btn btn-primary" name="sendEncryptedFileBtn" id="sendEncryptedFileBtn" >Send</button>
                    </a>
                  {%elif doesp.status == 'Re-Encrypted File Sent to Owner' %}
                  None
                  <!-- <a href="javascript:{document.getElementById('encryptOwnerFile{{doesp.id}}').submit()}" >
                      <button type="submit" class="btn btn-success" name="encryptFileBtn" id="encryptFileBtn" disabled>Encrypt</button>
                      </a>
                      <br>
                      <a href="javascript:{document.getElementById('sendEncryptedFile{{doesp.id}}').submit()}" >
                      <button type="submit" class="btn btn-success" name="sendEncryptedFileBtn" id="sendEncryptedFileBtn" disabled>Sent</button>
                    </a> -->
                    {%elif doesp.status == 'File Uploaded' %}
                    None
                  <!-- <a href="javascript:{document.getElementById('encryptOwnerFile{{doesp.id}}').submit()}" >
                      <button type="submit" class="btn btn-success" name="encryptFileBtn" id="encryptFileBtn" disabled>Encrypt</button>
                      </a>
                      <br>
                      <a href="javascript:{document.getElementById('sendEncryptedFile{{doesp.id}}').submit()}" >
                      <button type="submit" class="btn btn-success" name="sendEncryptedFileBtn" id="sendEncryptedFileBtn" disabled>Sent</button>
                    </a> -->
                  {%else%}
                    <a href="javascript:{document.getElementById('encryptOwnerFile{{doesp.id}}').submit()}" >
                    <button type="submit" class="btn btn-primary" name="encryptFileBtn" id="encryptFileBtn">Encrypt</button>
                    </a>
                    <!-- <a href="javascript:{document.getElementById('sendEncryptedFile{{doesp.id}}').submit()}" >
                    <button type="submit" class="btn btn-primary" name="sendEncryptedFileBtn" id="sendEncryptedFileBtn">Send</button> -->
                  </a>
                </td>
                {% endif %}
              </tr>

              <!-- FORM:Encrypt file -->
              <form action="{% url 'encdec:reEncryptFile' doesp.id %}" id="encryptOwnerFile{{doesp.id}}" method="post">
                    {% csrf_token %}
                    <!-- <input type="hidden" name=""> -->
                </form>

                <!-- Send encrypted file -->
                <form action="{% url 'encdec:sendReEncryptedFiles' doesp.id %}" id="sendEncryptedFile{{doesp.id}}" method="post">
                  {% csrf_token %}
                  <!-- <input type="hidden" name=""> -->
              </form>
              {% endfor %}

            </tbody>
          </table>
    </div>
{% endblock %}